//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Junisha_CSharp_Zero_App0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseChapters
    {
        public CourseChapters()
        {
            this.Progress = new HashSet<Progress>();
        }
    
        public int chapter_id { get; set; }
        public string chapter_title { get; set; }
        public string chapter_content1 { get; set; }
        public string chapter_content2 { get; set; }
        public string chapter_content3 { get; set; }
    
        public virtual ICollection<Progress> Progress { get; set; }
    }
}
