//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Junisha_CSharp_Zero_App0.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JunishaDBEntities : DbContext
    {
        public JunishaDBEntities()
            : base("name=JunishaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CourseChapters> CourseChapters { get; set; }
        public DbSet<Gender> Gender { get; set; }
        public DbSet<Progress> Progress { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
