//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Junisha_CSharp_Zero_App0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int progress_id { get; set; }
        public int user_id { get; set; }
        public int chapter_id { get; set; }
        public string progress_data { get; set; }
    
        public virtual CourseChapters CourseChapters { get; set; }
        public virtual Users Users { get; set; }
    }
}
