//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Junisha_CSharp_Zero_App0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Progress = new HashSet<Progress>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_pass { get; set; }
        public int gender_id { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Progress> Progress { get; set; }
    }
}
